### ISSUE TITLE
Seeking with mouse broken

### ISSUE THREAD

**Issue by tranzystorek-io** [LeoRiether/tori#23]
When trying to seek with mouse click, the actual position seems to be not absolute but "adds up" to the current position. See recording below.

I am suspecting this is because Void has updated to mpv 0.36 which could include breaking API changes, and libmpv-sirno seems to support mpv up to 0.35.

**To Reproduce**

See the following example:

![tori_seek_bug](https://github.com/LeoRiether/tori/assets/5671049/622368aa-2554-40eb-a2f8-7ba60efe9e9f)

**Expected behavior**

Mouse seek should seek to the position of the cursor.

**System Information (please complete the following information):**

 - OS: Void Linux
 - tori version 0.2.4
 - mpv 0.36.0

**Comment by LeoRiether** [comment]
Oh, that's caused by a [refactor](https://github.com/LeoRiether/tori/commit/62da97294008e19b2c6d6d1e455b9e150b6a1ed5#diff-6f206fe8d56f754ac27a928356431acc6729a192973771a297b1713470317fbaR77-R79) actually... `seek_absolute` has always been bugged in libmpv-sirno, but somehow I forgot about it ~~even though there's a comment saying it's broken right above~~. I'll just revert this change and it should work again!
