### ISSUE TITLE
Playlists folder

### ISSUE THREAD

**Issue by Ved-un** [LeoRiether/tori#3]
Hello.    
Thank you for your program, I just found it.    

I wanted to ask you - is it possible that the playlists folder is created in the tori configuration folder?

**Comment by LeoRiether** [comment]
Hello and thank you for trying out tori and opening an issue.

It is possible to change the playlists folder! By default, tori creates the playlists folder in `XDG_MUSIC_DIR/tori`, but you can change the location by modifying the configuration file. In your case, it should be located at `/home/elem/.config/tori.yaml`, so you should open (or create) this file and add this line to it:

```yaml
playlists_dir: /home/elem/.config/tori-playlists
```

Of course, you could change the path to whatever you'd like.

You may also be interested in other configuration options, like keybindings, which are [detailed in the docs](https://leoriether.github.io/tori/configuration/).

I hope this helps! Let me know if you have any further questions or issues.

**Comment by Ved-un** [comment]
Thank you for the information.    

I have another question - what does this error mean?    
This package was installed from the AUR.    
    
![flameshot_133](https://github.com/LeoRiether/tori/assets/48730277/569ed0e3-fd4f-41ef-8338-b1441182110c)

**Comment by LeoRiether** [comment]
Well, it appears that the issue may be related to your installation of PipeWire rather than tori directly (I'm guessing `pw` stands for pipewire). Also, I could not reproduce the error on my own machine.

To confirm this, you can try running `mpv /path/to/some/audio.mp3` to see if mpv can play the mp3. If it displays the same error, then the issue is likely  with your PipeWire installation.

Maybe reinstalling PipeWire will fix the issue -- there are installation instructions in [the arch wiki](https://wiki.archlinux.org/title/PipeWire) -- but I'm afraid this is the best advice I can give you right now.

**Comment by Ved-un** [comment]
Absolutely right, I did not have the pipewire package installed. That error is gone now.    
Then maybe it should be marked as a dependency, or not?

**Comment by Ved-un** [comment]
I'll close this issue as a done deal.    
I have one more question, but I'll open it later.

**Comment by LeoRiether** [comment]
> Then maybe it should be marked as a dependency, or not?

You're right, maybe it should. I'll need to investigate this further though, because tori uses mpv as an audio backend, so I expected pipewire to be a dependency of mpv, not tori.
